# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter:  <%= ENV['DATABASE_ADAPTER'] || "postgresql" %>
  encoding: <%= ENV['DATABASE_ENCODING'] || "unicode" %>
  # database: <%= ENV['DATABASE_NAME'] || "spotlight" %>
  pool:     <%= ENV['DATABASE_POOL'] || 5 %>
  username: <%= ENV['DATABASE_USERNAME'] || "spotlight" %>
  password: <%= ENV['DATABASE_PASSWORD'] || "spotlight" %>
  # host:     <%= ENV['DATABASE_HOST'] || "localhost" %>
  host:     <%= ENV['DATABASE_HOST'] || "db" %>
  port:     <%= ENV['DATABASE_PORT'] || 5432 %>
  ssl:      <%= ENV['DATABASE_SSL'] || "disable" %>
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   database: db/development.sqlite3

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  database: db/test.sqlite3

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || "spotlight" %>
  host: db
